export default [
  {
    material: "Dummy Název",
    balicilinka: "Linka",
    format: "33x66",
    prumer: "6",
    delka: "-",
    sirka: "-",
    vyska: "3.7",
    pvc: "detail",
    vyrobce: "test",
    id: 1,
    odkaz: "/kniha/acidumfolicum",
  },
  {
    material: "Dummy Název",
    balicilinka: "Linka",
    format: "33x66",
    prumer: "10",
    delka: "-",
    sirka: "-",
    vyska: "5.5",
    pvc: "detail",
    vyrobce: "test",
    id: 2,
    odkaz: "/kniha/agen5",
  },
  {
    material: "Dummy Název",
    balicilinka: "Linka",
    format: "33x66",
    prumer: "15",
    delka: "-",
    sirka: "-",
    vyska: "5.5",
    pvc: "detail",
    vyrobce: "test",
    id: 3,
    odkaz: "/kniha/agen5",
  },
];
